### ISSUE TITLE
Question regarding reproducing some results reported in the paper.

### ISSUE THREAD

**Issue by mikelmh025** [stevliu/self-conditioned-gan#3]
Hi there,

Thanks for the great paper and excellent implementation. Currently me and my team are working on a similar task as the one proposed in your paper. I noticed you got FID 28.08 of GAN on Cifar10, which I have a difficult time to reproduce. The results I got are: 
GAN: fid = 114 (200 epoch)
GAN: fid = 116 (800 epoch)
DC-GAN fid = 125 (200 epoch)

I have two guesses:
1. There are some issues with the model I use, maybe I need to tune it. In that case, I wonder if you can share some experience with tuning a traditional GAN/ DC_GAN on cifar10. Or maybe point me to some of the code you guys used.

2. My FID calculation has a bug. The code I used to calculate Fid says self-conditioned-gan achieve 17 fid, which is the same as the numbers in your paper. The only different is that self-conditioned-gan generate sample results by producing a '.npz' file while I generate sample by loading the checkpoint and generate 60k png images. Does this seems right to you? Or I am making a stupid mistake :<

################ code start ###########
def gen(g, num_samples=60000, latent_size=100, path="images"):
    for i in range(num_samples):
        # Sample noise as generator input
        z = Variable(Tensor(np.random.normal(0, 1, (1, latent_size))))
        gen_imgs = g(z)

        save_image(gen_imgs.data[0], os.path.join(path, f"{i}.png"), normalize=True)

        if not i % 1000:
            print(i)

**Comment by stevliu** [comment]
Hi, 

Thanks for your interest in the paper. To reproduce the results for vanilla GAN, you can run `python train.py configs/cifar/unconditional.yaml`, which trains an unconditional DC-GAN on CIFAR10. You can find the default hyperparameters we use in the config file. 

It should not matter whether the images are saved as '.png' or all saved in an '.npz' file, as long as they are normalized properly (in [0, 255]). FID > 100 suggests a very poor model, so if the samples are visually fine, this may suggest that the FID script has some problems.

**Comment by mikelmh025** [comment]
Thanks for the help! Will update after figuring out the bug. 👍

**Comment by mikelmh025** [comment]
Thanks for the help. I retrain the model by using **python train.py configs/cifar/unconditional.yaml**  and got a much better result. I tried to train the model for 200 epoch a couple times and achieved Fid of 58 - 62, and IS of 4.98. This result is much better than my previous and a closer score to the result your paper reported. 

However I am still curious how did you guy get Fid lower than 30 by using DC_GAN.

**Comment by stevliu** [comment]
Hi,

We have rerun the command and were able to achieve an FID of 28.34 at 150k iterations (around 150 epochs). Across all experiments, we're reporting the best number we see across training. Are you able to reproduce the number for earlier iterations? You can run the command `python metrics.py configs/cifar/unconditional.yaml --fid --every 10000` to verify this. 

GAN training frequently diverges if you train it for too long, especially when training without regularization (as we do for CIFAR).

**Comment by mikelmh025** [comment]
Thanks for the response! I have notice that the FID result from your script does able to get FID of 27-34. There might be a bug in my code.

When I was trying to run your metrics.py, I notice the code kept complaining about fail to load the check point. My code have would show similar bug when I was trying to load the save_dict:

### code ###
model = Generator(nlabels=1, conditioning = 'unconditional' )
    model.load_state_dict(torch.load(PATH))
    model.eval()
###
RuntimeError: Error(s) in loading state_dict for Generator:
        Missing key(s) in state_dict: "fc.weight", "fc.bias", "conv1.weight", "conv1.bias", "bn1.bn.weight", "bn1.bn.bias", "bn1.bn.running_mean", "bn1.bn.running_var", "conv2.weight", "conv2.bias", "bn2.bn.weight", "bn2.bn.bias", "bn2.bn.running_mean", "bn2.bn.running_var", "conv3.weight", "conv3.bias", "bn3.bn.weight", "bn3.bn.bias", "bn3.bn.running_mean", "bn3.bn.running_var", "conv_out.0.weight", "conv_out.0.bias". 
        Unexpected key(s) in state_dict: "it", "generator", "discriminator", "g_optimizer", "d_optimizer". 
###
output/cifar/unconditional/results iteration 60000 FID: 32.00206078682106
Computing for model_00170000.pt
Getting features from penultimate
=> Loading checkpoint from local file... ././output/cifar/unconditional/chkpts/model_00170000.pt
Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.fc.weight", "module.fc.bias", "module.conv1.weight", "module.conv1.bias", "module.bn1.bn.weight", "module.bn1.bn.bias", "module.bn1.bn.running_mean", "module.bn1.bn.running_var", "module.conv2.weight", "module.conv2.bias", "module.bn2.bn.weight", "module.bn2.bn.bias", "module.bn2.bn.running_mean", "module.bn2.bn.running_var", "module.conv3.weight", "module.conv3.bias", "module.bn3.bn.weight", "module.bn3.bn.bias", "module.bn3.bn.running_mean", "module.bn3.bn.running_var", "module.conv_out.0.weight", "module.conv_out.0.bias". 
        Unexpected key(s) in state_dict: "fc.weight", "fc.bias", "conv1.weight", "conv1.bias", "bn1.bn.weight", "bn1.bn.bias", "bn1.bn.running_mean", "bn1.bn.running_var", "bn1.bn.num_batches_tracked", "conv2.weight", "conv2.bias", "bn2.bn.weight", "bn2.bn.bias", "bn2.bn.running_mean", "bn2.bn.running_var", "bn2.bn.num_batches_tracked", "conv3.weight", "conv3.bias", "bn3.bn.weight", "bn3.bn.bias", "bn3.bn.running_mean", "bn3.bn.running_var", "bn3.bn.num_batches_tracked", "conv_out.0.weight", "conv_out.0.bias". 
=> Loading checkpoint from local file... ././output/cifar/unconditional/chkpts/model_00170000.pt
Warning: Could not find generator_test in checkpoint!
Loaded iteration: 170000
Sampling with uniform distribution over 1 labels
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 501/501 [00:27<00:00, 18.53it/s]
Inferred dataset: cifar
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/py3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
output/cifar/unconditional/results/samples.npz
Inferred name cifar
WARNING:tensorflow:From gan_training/metrics/fid.py:208: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From gan_training/metrics/fid.py:209: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 250/250 [01:19<00:00,  3.13it/s]
using cached image stats for cifar
FID: 34.31734260614843
output/cifar/unconditional/results iteration 170000 FID: 34.31734260614843

**Comment by mikelmh025** [comment]
I wonder how did you load the model and generate the sample.npz file?

**Comment by stevliu** [comment]
Thanks for the update. 

Our state dict saves not only the generator, but also the optimizers, iteration number, and discriminator. It's currently complaining about the format of the state dict. You may want to try saving your state dict as `{'generator': your_generator.state_dict()}`

**Comment by mikelmh025** [comment]
Yeah! I was able to load the model and generate images!!! Currently I got fid of 55 from my end. After testing a couple things I believe I have the wrong way to generate the images. 

## my code ##

def gen(g, num_samples=60000, latent_size=128, path="images"):

    for i in range(num_samples):
        # Sample noise as generator input
        z = Variable(Tensor(np.random.normal(0, 1, (1, latent_size))))
        y = Variable(Tensor(np.random.normal(0, 0, (1, latent_size))))
        gen_imgs = g(z,y)

        save_image(gen_imgs.data[0], os.path.join(path, f"{i}.png"), normalize=True)

        if not i % 1000:
            print(i)


I calculated the fid between my generated images and the sample.npz file generated from metric.py. It has fid of 30, which means there must be something wrong with how I generate the images. Can you explain a little bit about how you generate your final images results? 

Also thanks for being helpful ! 👍 :)

**Comment by stevliu** [comment]
One potential problem can be the normalization --- our FID script expects the images to be normalized in [0, 255] before feeding into the Inception network. You may want to try seeding the latent and seeing if the generated images from our script and your script are the same.

**Comment by junyanz** [comment]
maybe we can add a note to the FID code or README regarding the range of input.
