### ISSUE TITLE
How do I code conditional GAN for stacked mnist dataset?

### ISSUE THREAD

**Issue by TanmDL** [stevliu/self-conditioned-gan#4]
Thank you for sharing the code. Please share the code of the stacked MNIST dataset for conditional GAN. Actually I have some quarries regarding the conditional gan for stacked mnist dataset?
1. for the real class conditional which class information will I need to feed into the discriminator? Although, the real data is associated with three classes. I am confused about this portion.

**Comment by stevliu** [comment]
Hi!

We have included code for the stacked-MNIST experiments, and they are found under `configs/stacked_mnist/`. The code for producing the stacked-MNIST dataset is here: 
https://github.com/stevliu/self-conditioned-gan/blob/master/gan_training/inputs.py#L105

Here, we assign each tuple of three classes (a, b, c) to a number in {0, ..., 999} by doing 100 * a + 10 * b + c. Then, we can feed this in the discriminator the same way as we do for standard class-conditional training.
