### ISSUE TITLE
Got grey scale while using 3 channel G

### ISSUE THREAD

**Issue by mikelmh025** [stevliu/self-conditioned-gan#5]
I wonder if this happens to you guys. When I was trying try a GAN, let's say DC_GAN, on VGG face dataset. The dataset includes faces of different people. The training process on 32x32 image was nice and smooth, but when changed to 64x64 or above I will get some grey scale images and some RGB images. 

![image](https://user-images.githubusercontent.com/38229852/97124015-9e116d80-16eb-11eb-8643-8dfb568e8545.png)

**Comment by stevliu** [comment]
Hi,

We haven't experienced this problem exactly. One possible explanation for this is that there are grey-scale images in the VGG dataset, and our method tries to capture that (but clearly overshoots in this case). 

We have experienced some occasional training instability issues when using DCGAN on higher resolution images. Some potential ways you can fix this is by adding some small discriminator regularization (by changing `d_reg` to something positive), or by switching to a larger architecture (like the `resnet2.py` architecture).
